title:              Ben Yoo | Senior Product Manager
email:              ben.jin.yoo@gmail.com
description:        Senior Product Manager & AI Strategist. Specializing in high-impact digital modernization and large-scale transformation.
author:             Ben Yoo
baseurl:            ""
url:                "https://benyoo.github.io"

# Social Profiles
twitter_username:   be_nyoo
github_username:    benyoo
facebook_username:  
instagram_username: be_nyoo 
linkedin_username:

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
